routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/send', 'EmailController@send');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', 'AuthController@login');
    Route::post('/', 'AuthController@doLogin');

    Route::group(['middleware' => 'auth'], function () {
        Route::group(['prefix' => 'api'], function () {
            Route::get('/logout', 'AuthController@logout');
            Route::post('/features', 'CategoriesController@createFeature');
            Route::get('/allCategories', 'CategoriesController@getAllCategories');
            Route::delete('/features/{id}', 'CategoriesController@deleteFeature');
            Route::get('/allProjectTypes', 'ProjectTypesController@getAllTypes');

            Route::group(['prefix' => 'categories'], function () {
                Route::get('/', 'CategoriesController@getAllCategories');
                Route::get('/{category}', 'CategoriesController@getCategory');
                Route::delete('/{id}', 'CategoriesController@delete');
                Route::post('/', 'CategoriesController@create');
                Route::post('/{category}', 'CategoriesController@update');
                Route::post('/{category}/image', 'CategoriesController@addImage');
                Route::delete('/image/{id}', 'CategoriesController@deletePhoto');
            });

            Route::group(['prefix' => 'project_types'], function () {
                Route::get('/', 'ProjectTypesController@getSubTypes');
                Route::get('/{project_type}', 'ProjectTypesController@getSubType');
                Route::delete('/{id}', 'ProjectTypesController@delete');
                Route::post('/', 'ProjectTypesController@create');
                Route::post('/{project_type}', 'ProjectTypesController@update');
            });

            Route::group(['prefix' => 'products'], function () {
                Route::get('/', 'ProductController@index');
                Route::get('/{product}', 'ProductController@getProduct');
                Route::post('/', 'ProductController@create');
                Route::post('/{product}/image', 'ProductController@addImage');
                Route::post('/{product}', 'ProductController@update');
                Route::delete('/{product}', 'ProductController@delete');
                Route::delete('/image/{id}', 'ProductController@deletePhoto');
            });
        });

        Route::any('{all?}', function () {
            return view('admin.main');
        })->where(['all' => '.*']);
    });
});

Route::group(['namespace' => 'Index'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/styles/{style}', 'HomeController@style');
    Route::get('/project/{project}', 'HomeController@project');
    Route::get('/uslugi-i-ceny', 'HomeController@uslugi');
    Route::get('/portfolio', 'HomeController@portfolio');
    Route::get('/portfolio/{slug}', 'HomeController@portfolioSubType');
    Route::get('/styles', 'HomeController@styles');
    Route::get('/contacts', 'HomeController@contact');
    Route::get('/reviews', 'HomeController@reviews');
});

Route::get('locale/{locale?}',
    [
        'as' => 'locale.setlocale',
        'uses' => 'LocaleController@setLocale'
    ]);

app/Http/Controllers/Admin/ProjectTypesController.php
<?php 

namespace App\Http\Controllers\Admin;

use App\ProjectType;

use Illuminate\Http\Request;
use Illuminate\Database\Query\Builder;
use App\Http\Controllers\Controller;

class ProjectTypesController extends Controller {

    public function getSubTypes() {

        $types = ProjectType::where('parent_id', null)
                    ->withCount('children')
                    ->get();
        
        return compact('types');
    }

    public function getSubType($id) {

        $type = ProjectType::where('id', $id)->first();

        $parent_id = $type->id;   

        $children = ProjectType::where('parent_id', $parent_id)
                    ->withCount('children')
                    ->get();
        $freeTypes = ProjectType::withCount('children')
                          ->where('id','<>',$parent_id)
                          ->where(function($query) use ($parent_id) {
                                $query->where('parent_id','<>',$parent_id)
                                      ->orWhereNull('parent_id');
                          })
                          ->get();
        
        return compact('type', 'children', 'freeTypes');
    }

    public function getAllTypes() {
        return ProjectType::get();
    }

	public function create(Request $request) {
        $data = [
            'name' => $request->input('name'),
            'slug' => $request->input('slug'),
            'parent_id' => $request->input('parent_id')
        ];

        ProjectType::create($data);

		return ['result' => 'success'];
	}

	public function update(ProjectType $type, Request $request)
    {
        $data = [
            'name' => $request->input('name'),
            'slug' => $request->input('slug'),
            'parent_id' => $request->input('parent_id')
        ];

        $type->update($data);
        $type->parent_id = $request->input('parent_id');
        $type->save();

        return ['result' => 'success'];
    }	

	public function delete($id)
    {
        $type=ProjectType::where('id', $id)->first();
        
        $type->delete();

        return ['result' => 'success'];
    }	
    
}

resources/views/index/contact.blade.php
@extends('index.layout')

@section('head')
  <title>Design - Kupriyanova Vera</title>
@endsection

@section('content')

<div class="page-top-image">
    <div class="image-back">
        <img src="/assets/index/img/price.jpg" alt="">
    </div>
    <div class="title page">
      <h1>Контакты</h1>
      <h2>Куприянова Вера, Минск, Беларусь</h2>
    </div>
</div>
<div class="content white link">
  <div class="contacts">
    <form class="contact-form" method="POST" action="/send">
        <input class="short" placeholder="Имя" name="firstName" type="text">
        <input class="short" placeholder="Фамилия" name="secondName" type="text">
        <input placeholder="Email" name="email" type="text">
        <input placeholder="Телефон" name="number" type="text">
        <textarea placeholder="Ваше сообщение" name="text" id="" cols="30" rows="4"></textarea>
        <button type="submit">отправить</button>
    </form>
    <div class="info">
      <h3>Жду вашего звонка</h3>
      <p>
        Необходима консультация? Желаете заказать дизайн-проект? Звоните в любой день до 20:00. 
        Буду рада ответить на все Ваши вопросы.
      </p> 
      <p>
        c 10:00 до 20:00
        <br>  
        Каждый день. Без выходных.
      </p>
      <a href="">+375 29 159-45-81</a>
    </div>
  </div>
</div>
<div class="content">
  <div class="footer">
    <div class="text">© 2018 Вера Куприянова. Все права защищены.</div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
@endsection

resources/views/index/layout.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-RU" lang="ru-RU">
	<head>
		@yield('head')
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="description" content="Услуги по разработке дизайна интерьера и 3-д визуализации;">
		<meta name="keywords" content="разработка,создание,проект,планировочное решение,дизайн интерьера,дизайн-проект,рабочие чертежи,3d визуализация,мебель,авторский надзор,строительная компания,отделочные материалы,гостиная,спальня,кухня,детская,ванная">
		<meta name="generator" content="Parallels Presence Builder 12.0.7">
		<link rel="stylesheet" href="/assets/index/css/font-awesome.min.css">
		<link rel="stylesheet" href="/assets/index/css/animate.css">
		<link rel="stylesheet" href="{{ mix('/assets/index/css/app.css') }}">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
		<script src="/assets/index/js/wow.min.js"></script>
		<script src="/assets/index/js/siema.min.js"></script>
	</head>
	<body>
		<div class="burger-menu" id="menu-open">
			<span class="fa fa-bars"></span>
		</div>
		<header>
			<div class="wrapper">
				<div class="inner">
					<a href="/">
						<img width="180" src="/assets/index/img/logo.png" alt="">
						<img width="180" src="/assets/index/img/logo_name.png" alt="">
					</a>
					<nav>
						<li><a href="/">Главная</a></li>
						<li>
							<a href="/portfolio">Портфолио</a>
							<div class="hidden-menu">
								<ul>
									@foreach($types as $link)
										<li>
											<a href="/portfolio/{{$link->slug}}">
												<span>
													{{ $link->name }}
													<div class="line"></div>
												</span>
												@if($link->children_count) 
													<i class="fa fa-angle-right"></i>
												@endif
											</a>
											@if ($link->children_count)
												<div class="hidden-menu">
													<ul>
														@foreach($link->children as $childlink)
															<li>
																<a href="/portfolio/{{$childlink->slug}}">
																	<span>
																		{{ $childlink->name }}
																		<div class="line"></div>
																	</span>
																</a>
															</li>
														@endforeach
													</ul>
												</div>
											@endif
										</li>
									@endforeach
								</ul>
							</div>
						</li>
						<li><a href="/uslugi-i-ceny">Услуги и цены</a></li>
						<li><a href="/styles">Стили</a></li>
						<li><a href="/reviews">Отзывы</a></li>
						<li><a href="/contacts">Контакты</a></li>
					</nav>
					<div class="tel">
						<a href="#">+375 29 159 45 81</a>
					</div>
					<div class="soc-networks">
						<a href="mailto: veradesign@bk.ru"><span class="fa fa-envelope"></span></a>
						<a target="_blank" href="https://www.facebook.com/kupriyanova.by/"><span class="fa fa-facebook"></span></a>
						<a target="_blank" href="https://www.instagram.com/veradesignminsk/?hl=ru"><span class="fa fa-instagram"></span></a>
					</div>
				</div>
			</div>
		</header>
		<div class="main-content">
			<div class="container">
				@yield('content')
			</div>
		</div>
	</body>
	<script>
		new WOW().init();
		window.onload = function() {
			$("#menu-open").click(function() {
				$("header").toggleClass('open');
				$("#menu-open > span").toggleClass('light');
			});
		};
	</script>
</body>
</html>

resources/views/index/portfolio.blade.php
@extends('index.layout')

@section('head')
  <title>Design - Kupriyanova Vera</title>
	<link rel="stylesheet" href="/assets/index/css/easyzoom.css" />
@endsection

@section('content')
<div class="page-top-image">
    <div class="image-back">
        <img src="/assets/index/img/price.jpg" alt="">
    </div>
    <div class="title page">
        <h1>Портфолио</h1>
        @if ($type)
            <h2>{{ $type->name }}</h2>
        @else
            <h2>Куприянова Вера, Минск, Беларусь</h2>
        @endif
    </div>
</div>
<div class="content white link">
    <div class="block">
        <h3 class="center-title">мои работы</h3>
        <h5 class="center-subtitle">
            На данной странице представлена часть разработанных мною проектов.
            Каждый дизайн-проект создан исходя из пожеланий и вкусовых предпочтений клиента. И
            помните, что безграничную фантазию может ограничить лишь бюджет на ремонт, а безграничное
            число пожеланий – размер помещения.
        </h5>
        <div class="line"></div>
    </div>
    <div class="project-types-menu">
        <ul>
            @foreach($types as $link)
                <li>
                    <a href="/portfolio/{{$link->slug}}">
                        <span>
                            {{ $link->name }}
                        </span>
                    </a>
                    @if ($link->children_count)
                        <ul>
                            @foreach($link->children as $childlink)
                                <li>
                                    <a href="/portfolio/{{$childlink->slug}}">
                                        <span>
                                            {{ $childlink->name }}
                                        </span>
                                    </a>
                                </li>
                            @endforeach
                        </ul>
                    @endif
                </li>
            @endforeach
        </ul>
    </div>
    @foreach($projects as $key=>$project)
        <div class="project-item">
            <h2>{{ $project->name }}</h2>
            <h6>{{ $project->style }} &ndash; {{ $project->size }} м<sup>2</sup></h6>
            <div class="project-preview mt">
                <div class="easyzoom {{ $key }} easyzoom--overlay easyzoom--with-thumbnails">
                    @if(!empty($project->first_photo))
                    <a href="{{$project->first_photo->image_url}}">
                        <img src="{{$project->first_photo->image_url}}" alt=""/>
                    </a>
                    @endif
                </div>

                <ul class="thumbnails {{ $key }}">
                    @foreach($project->gallery as $key=>$photo)
                        @if($key < 9)
                            <li>
                                <a href="{{ $photo->image_url }}" data-standard="{{ $photo->image_url }}">
                                    <img src="{{ $photo->image_url }}" alt="{{ $project->name }}. {{ $photo->alt }}" />
                                </a>
                            </li>
                        @endif
                    @endforeach
                </ul>
                <a target="_blank" href="/project/{{$project->slug}}">подробнее</a>
            </div>
        </div>
    @endforeach
</div>
<div class="content">
    <div class="footer">
      <div class="text">© 2018 Вера Куприянова. Все права защищены.</div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="/assets/index/js/easyzoom.js"></script>
<script>
    // Instantiate EasyZoom instances
    var $easyzoom = $('.easyzoom').easyZoom();

    for (var i = 0; i < Object.keys($easyzoom).length; i++) {
        let api = $easyzoom.filter('.easyzoom--with-thumbnails.' + i).data('easyZoom');  
        $('.thumbnails.' + i).on('click', 'a', function(e) {
            var $this = $(this);

            e.preventDefault();

            // Use EasyZoom's `swap` method
            api.swap($this.data('standard'), $this.attr('href'));
        });
    }
</script>
@endsection

resources/views/index/project.blade.php
@extends('index.layout')

@section('head')
  <title>Design - Kupriyanova Vera</title>
  <link href="/assets/index/css/simplelightbox.css" rel="stylesheet" type="text/css">
@endsection

@section('content')

<div class="page-top-image">
    <div class="image-back">
        <img src="{{$project->first_photo->image_url}}" alt="Дизайн. Минск. Вера Куприянова. {{ $project->name }}">
    </div>
    <div class="title page">
        <h1>{{ $project->name }}</h1>
        <h2>{{ $project->style }} &ndash; {{ $project->size }} м<sup>2</sup></h2>
    </div>
</div>
<div class="content white">
  <div class="block">
    <div class="styles white">
      <div class="info-block wide">
        <h2>ВИЗУАЛИЗАЦИИ ПРОЕКТА</h2>
        <div class="line left"></div>
        <div class="info-block white project">
          <div>
                  {!! $project->about !!}
          </div>
          <a class="review-btn" href="/reviews">оставить отзыв</a>
        </div>
      </div>
    </div>
    <div class="content link">
      <div class="gallery-block">
        <div class="gallery">
          @foreach($project->gallery as $photo)
            <a href="{{ $photo->image_url }}"><img src="{{ $photo->image_url }}" alt="" title="{{ $project->name }}. {{ $photo->alt }}" /></a>
          @endforeach
        </div>
      </div>
    </div>
    <div class="footer" style="margin-top: 20px">
      <div class="text">© 2018 Вера Куприянова. Все права защищены.</div>
    </div>
  </div>
  
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="/assets/index/js/simple-lightbox.min.js"></script>
<script>
  $(function(){
		$('.gallery a').simpleLightbox();
  });
</script>
@endsection

resources/views/index/style.blade.php
@extends('index.layout')

@section('head')
  <title>Design - Kupriyanova Vera</title>
  <link href="/assets/index/css/simplelightbox.css" rel="stylesheet" type="text/css">
@endsection

@section('content')

<div class="page-top-image">
    <div class="image-back">
        <img src="/assets/index/img/price.jpg" alt="">
    </div>
    <div class="title page">
      <h1>{{ $style->name }}</h1>
    </div>
</div>
<div class="content white link">
  <div class="text-block">
    <h5>Описание</h5>  
    <p>
      {{ $style->about }}
    </p>
    <h5>Концептуальное решение</h5>
    <ul>
      @foreach($style->features as $feature) 
        <li>{{ $feature->text }}</li>
      @endforeach
    </ul>
    <h5>Примеры</h5>
  </div>
  <div class="gallery">
      @foreach($style->gallery as $photo) 
			  <a href="{{ $photo->image_url }}"><img src="{{ $photo->image_url }}" alt="{{ $photo->alt }}"/></a>
      @endforeach
      <div class="clear"></div>
  </div>
</div>
<div class="content">
  <div class="footer">
    <div class="text">© 2018 Вера Куприянова. Все права защищены.</div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="/assets/index/js/simple-lightbox.min.js"></script>
<script>
  $(function(){
		var $gallery = $('.gallery a').simpleLightbox();
	});
</script>
@endsection

resources/views/index/styles.blade.php
@extends('index.layout')

@section('head')
  <title>Design - Kupriyanova Vera</title>
	<link rel="stylesheet" href="/assets/index/css/easyzoom.css" />
@endsection

@section('content')
<div class="page-top-image">
    <div class="image-back">
        <img src="/assets/index/img/price.jpg" alt="">
    </div>
    <div class="title page">
        <h1>Cтили</h1>
        <h2>Куприянова Вера, Минск, Беларусь</h2>
    </div>
</div>
<div class="content white link">
    <div class="block">
        <h3 class="center-title">Популярные стили</h3>
        <h5 class="center-subtitle">
            Стиль оказывает влияние на планировку помещений, 
            цветовую гамму, материал исполнения предметов интерьера, 
            их расположение, форму, стоимость самого ремонта.
        </h5>
        <div class="line"></div>
    </div>
    <div class="styles-container">
        @foreach ($styles as $style)
            <div class="style">
                <a target="_blank" href="/styles/{{ $style->slug }}">
                <div class="img-block">
                    <img src="{{ $style->image_url }}" alt="{{ $style->name }}. Популярные стили.">
                    <div class="backdrop">
                        <div class="border">
                        <h5>подробнее</h5>
                    </div>
                    </div>
                </div> 
                </a>
                <h4><a target="_blank" href="/styles/{{ $style->slug }}">{{ $style->name }}</a></h4>
            </div>
        @endforeach
    </div>
</div>
<div class="content">
    <div class="footer">
      <div class="text">© 2018 Вера Куприянова. Все права защищены.</div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
@endsection

resources/views/index/uslugi.blade.php
@extends('index.layout')

@section('head')
  <title>Design - Kupriyanova Vera</title>
@endsection

@section('content')

<div class="page-top-image">
    <div class="image-back">
        <img src="/assets/index/img/price.jpg" alt="">
    </div>
    <div class="title page">
        <h1>Услуги и цены</h1>
        <h2>Куприянова Вера, Минск, Беларусь</h2>
    </div>
</div>
<div class="content white link">
    <div class="block">
        <h3 class="center-title">Дизайн Интерьера Вашей Квартиры</h3>
        <div class="line"></div>
        <div class="services">
            <ul>
                <li class="name">
                    <h3>Планировочное решение</h3>
                </li>
                <li class="price">
                    <span>
                        <span class="currency">$</span><span>4</span>
                    </span> 
                    <p>За метр квадратный</p>
                </li>
                <li class="text">
                    <p>обмерный план</p>
                    <p>планировочное решение</p>
                    <p>план монтажа / демонтажа перегородок</p>
                    <p>план с расстановкой мебели и оборудования</p>
                </li>
            </ul>
            <ul>
                <li class="name">
                    <h3>Эскизный <br> дизайн-проект</h3>
                </li>
                <li class="price">
                    <span>
                        <span class="currency">$</span><span>16</span>
                    </span> 
                    <p>За метр квадратный</p>
                </li>
                <li class="text">
                    <p>обмерный план</p>
                    <p>планировочное решение</p>
                    <p>план монтажа / демонтажа перегородок</p>
                    <p>план с расстановкой мебели и оборудования</p>
                    <p>3D-визуализации помещений (по 2-3 ракурса)</p>
                </li>
            </ul>
            <ul>
                <li class="name">
                    <h3>Полный <br> дизайн-проект</h3>
                </li>
                <li class="price">
                    <span>
                        <span class="currency">$</span><span>24</span>
                    </span> 
                    <p>За метр квадратный</p>
                </li>
                <li class="text">
                    <p>эскизный-дизайн проект + </p>
                    <p>план с расстановкой мебели и оборудования</p>
                    <p>планы полов, потолков и расположения карнизов</p>
                    <p>план теплых полов</p>
                    <p>план освещения и связей групп светильников с выключателями</p>
                    <p>схема монтажа розеток</p>
                    <p>раскладка плитки (стены)</p>
                    <p>план размещения  и спецификация сантехнического оборудования</p>
                    <p>чертежи мебели на заказ (выполняются в случае необходимости)</p>   
                    <p>развёртки стен, ведомость отделки помещений (отделочные материалы)</p>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="content gray link">
    <div class="text-block">
        <h5>Дополнительные услуги</h5>
        <p>
            Сопровождение проекта (авторский надзор) - 300$ в месяц (выезд дизайнера на объект для беседы со строителями в начале каждого этапа ремонтно-отделочных работ и обзора завершённого этапа в присутствии заказчика).
        </p>
            
        <p>Выезд дизайнера на объект (разовый выезд) - 50$.</p>
        <p> Сопровождение при приобретении материалов, мебели и оборудования - 25$ за 2 часа.</p>   
        <p>Консультации и советы по выбору отделочных материалов, мебели и прочим вопросам можно получить по телефону или по интернету - бесплатно.</p>
        </p>
        <p>
        <br>
            * Стоимость актуальна при нахождении объекта в пределах 10км от МКАД - на более дальние расстояния - стоимость договорная.
            <br><br>
            ** Обращаем Ваше внимание, что, в соответствии с законодательством Республики Беларусь расчет за продаваемые товары осуществляется в белорусских рублях. Цены в иностранной валюте указаны для нерезидентов Республики Беларусь в случае заключения внешнеторгового договора.
            <br><br>
            *** Цены указаны в ознакомительных целях. Оплата производится в белорусских рублях по курсу НБ РБ на день расчета.
        </p>
    </div>
</div>
<div class="content white link">
    <div class="text-block">
        <h5>Техническое задание. Зачем оно нужно?</h5>
        <p>
            Техническое задание поможет Вам определиться в своих желаниях и увидеть картину ремонта в целом. 
            Вы столкнётесь с вопросами, о которых даже бы и не задумались на начальном этапе, а также найдете множество подсказок.
            <br><br>
            ТЗ необходимо осознано заполнить и прислать на почту <a href="mailto:veradesign@bk.ru">veradesign@bk.ru</a> для ознакомления.
            <br><br>
            Это поможет донести до дизайнера Ваши планы по поводу будущего интерьера, повлияет на сроки и качество выполняемых работ. Скачать
            техническое задание Вы можете, нажав на кнопку ниже.
        </p>
        <a href="#" class="gold">
            скачать
        </a>
    </div>
</div>
<div class="content accent link">
    <div class="text-block">
        <h5>ВНИМАНИЕ!</h5>
        <p>
            Обращаем Ваше внимание на то, что, вся информация на сайте носит рекламный характер 
            и не является публичной офертой, определяемой положениями статьи 464 Гражданского кодекса 
            Республики Беларусь. Для получения подробной информации о актуальной стоимости услуг, 
            а также о порядке заключения договора на услуги, пожалуйста, обращайтесь по указанным на 
            сайте телефонам.
        </p> 
    </div>
</div>
<div class="content">
    <div class="footer">
        <div class="text">© 2018 Вера Куприянова. Все права защищены.</div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
@endsection